services:
  - type: web
    name: airshare
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SERVER_URL
        fromService:
          name: airshare
          type: web
          property: url 